async (page,output)=>{
 const checks=[],errors=[],mutations=[];const check=(name,value)=>{if(!value)throw Error(name);checks.push(name)};
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')mutations.push(new URL(r.url()).pathname)});
 await page.unroute('**/api/home');await page.unroute('**/api/open_home_note');await page.unroute('**/api/home_layout');const base=page.url().split('#')[0];await page.mouse.up();await page.goto(base+'#home');await page.reload();await page.waitForFunction(()=>homeState?.configured&&state);
 const defaults=['status','next','focus','douyin','later'];
 const order=()=>page.evaluate(()=>[...document.querySelectorAll('#home-cards>[data-home-card]')].map(c=>c.dataset.homeCard));
 check('synthetic stage only',await page.locator('.tile-phase h3').textContent()==='测试阶段');
 check('five cards, not a report',await page.locator('#home-cards>[data-home-card]').count()===5);
 check('four current subjects are source backed',await page.locator('.status-record').count()===4);
 check('no homepage submenu in DOM',await page.locator('#homenav').count()===0);
 check('homepage menu and toggle are absent',await page.locator('#modulepanel').isHidden()&&await page.locator('#navtoggle').isHidden());
 check('no date picker or task completion controls',await page.locator('[data-home-day],#homeview input[type=checkbox]').count()===0);
 check('only two key next records on homepage',await page.locator('#homeview .schedule-record').count()===2);
 check('uncertain original date is not scheduled as confirmed',await page.locator('.schedule-record').first().textContent().then(t=>t.includes('原 ')&&t.includes('日期待确认')));
 check('unstarted plans remain deferred',await page.locator('[data-home-card=later]').textContent().then(t=>t.includes('早期规划')&&t.includes('尚未启动')));
 check('collection counters use actual fixture data',await page.locator('.collection-total strong').textContent()==='65'&&await page.locator('.collection-meta').textContent().then(t=>t.includes('已入库 1')));
 check('opening homepage does not mutate or call AI',mutations.length===0);
 {const r=await page.locator('[data-home-card=douyin] h2').boundingBox();await page.mouse.click(r.x+r.width/2,r.y+r.height/2);}await page.waitForTimeout(300);
 check('module card heading is a real full-card link',await page.evaluate(()=>currentModule==='douyin'));
 await page.locator('#homemodule').click();await page.waitForTimeout(300);
 {const r=await page.locator('[data-home-card=douyin] .collection-total').boundingBox();await page.mouse.click(r.x+r.width/2,r.y+r.height/2);}await page.waitForTimeout(300);
 check('module counter click enters its existing library',await page.evaluate(()=>currentModule==='douyin'));
 await page.locator('#homemodule').click();await page.waitForTimeout(300);
 await page.locator('.module-entry').focus();await page.keyboard.press('Enter');await page.waitForTimeout(300);
 check('module entry works from keyboard without fake future routes',await page.evaluate(()=>currentModule==='douyin'&&Object.keys(moduleRegistry).length===2));
 await page.locator('#homemodule').click();await page.waitForTimeout(300);
 await page.locator('[data-home-handle=douyin]').click();
 check('drag handle click does not navigate away',await page.evaluate(()=>currentModule==='home'));

 const jobsBefore=await page.evaluate(()=>JSON.stringify(state.jobs)),videosBefore=await page.evaluate(()=>JSON.stringify(state.videos));
 for(const width of [1440,1080,800,600,390,320]){
  await page.setViewportSize({width,height:920});await page.waitForTimeout(280);
  const r=await page.evaluate(()=>{const ws=document.querySelector('.workspace'),rail=document.querySelector('.module-rail').getBoundingClientRect();return{left:ws.getBoundingClientRect().left,right:ws.getBoundingClientRect().right,railRight:rail.right,overflow:document.documentElement.scrollWidth>innerWidth}});
  check(width+': content starts at primary rail',Math.abs(r.left-r.railRight)<1);
  check(width+': right edge fixed without overflow',Math.abs(r.right-width)<1&&!r.overflow);
  check(width+': no secondary navigation',await page.locator('#modulepanel').isHidden()&&await page.locator('#navtoggle').isHidden());
  check(width+': all cards and handles fit',await page.evaluate(()=>[...document.querySelectorAll('#home-cards article')].every(c=>{const r=c.getBoundingClientRect(),h=c.querySelector('.tile-handle').getBoundingClientRect();return r.width>180&&h.right<=r.right&&h.left>=r.left})));
 }
 await page.screenshot({path:output+'/home-cards-phone.png'});
 await page.setViewportSize({width:1440,height:920});await page.waitForTimeout(350);
 await page.locator('.status-record').first().click();
 check('status opens full evidence detail',await page.locator('#home-detail-content').textContent().then(t=>t.includes('准备完成、未验收')&&t.includes('测试状态')));
 check('detail outside click closes only detail',await page.locator('#homedetail').isVisible());await page.mouse.click(1380,880);
 check('outside dismissal works',await page.locator('#homedetail').isHidden());
 await page.locator('[data-home-card=later] .tile-record').first().click();
 check('future detail does not become a task',await page.locator('#home-detail-content').textContent().then(t=>t.includes('早期规划')&&t.includes('不标记完成')));await page.locator('#closehomedetail').click();
 let source=null;await page.route('**/api/open_home_note',async route=>{source=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'})});
 await page.locator('[data-home-card=status] [data-home-source]').click();
 check('source opens via selected ID only',source?.source==='current'&&!Object.hasOwn(source,'path'));
 await page.unroute('**/api/open_home_note');
 await page.route('**/api/open_home_note',route=>route.fulfill({status:400,contentType:'application/json',body:'{"error":"测试打开失败"}'}));
 await page.locator('[data-home-card=status] [data-home-source]').click();
 await page.waitForFunction(()=>document.getElementById('toast').textContent==='测试打开失败');check('source error is visible',await page.locator('#toast').textContent()==='测试打开失败');await page.unroute('**/api/open_home_note');
 await page.evaluate(async()=>{await api('navigation_motion',{mode:'on'});await refresh();applyHomeOrder(HOME_CARD_IDS);await persistHomeOrder()});
 check('default order accepted',JSON.stringify(await order())===JSON.stringify(defaults));
 const a=await page.locator('[data-home-handle=focus]').boundingBox(),b=await page.locator('[data-home-card=douyin]').boundingBox();
 await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+35,a.y+25);await page.waitForTimeout(80);
 check('drag picks up a floating card',await page.locator('.home-drag-preview').count()===1&&await page.evaluate(()=>homeDrag?.active));
 await page.mouse.move(b.x+b.width/2,b.y+100,{steps:14});await page.waitForTimeout(120);await page.mouse.up();await page.waitForTimeout(400);await page.evaluate(()=>homeSaveChain);
 const moved=await order();check('pointer drag changes DOM order',JSON.stringify(moved)!==JSON.stringify(defaults)&&moved.indexOf('focus')>defaults.indexOf('focus'));
 check('pointer capture and ghost clean up',await page.evaluate(()=>!homeDrag&&!document.body.classList.contains('home-sorting')&&document.querySelectorAll('.home-drag-preview').length===0));
 check('layout order saved in backend',await page.evaluate(async()=>JSON.stringify((await api('state')).home_card_order)===JSON.stringify(homeOrder)));
 await page.reload();await page.waitForFunction(()=>homeState?.configured&&state);await page.waitForTimeout(150);
 check('reload restores saved order',JSON.stringify(await order())===JSON.stringify(moved));
 const handle=page.locator('[data-home-handle=later]');await handle.focus();await page.keyboard.press('Space');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await page.evaluate(()=>homeSaveChain);await page.waitForTimeout(280);
 check('keyboard drag moves a card',JSON.stringify(await order())!==JSON.stringify(moved));
 check('keyboard move returns focus to handle',await page.locator('[data-home-handle=later]').evaluate(e=>e===document.activeElement));
 const beforeCancel=await order();await page.keyboard.press('Space');await page.keyboard.press('ArrowUp');await page.keyboard.press('Escape');await page.waitForTimeout(280);
 check('Escape cancels and restores layout',JSON.stringify(await order())===JSON.stringify(beforeCancel)&&await page.evaluate(()=>!homeDrag));
 const down=await page.locator('[data-home-handle=later]').boundingBox();await page.mouse.move(down.x+10,down.y+10);await page.mouse.down();await page.mouse.move(down.x-25,down.y+30);await page.waitForTimeout(100);await page.setViewportSize({width:1200,height:920});await page.mouse.up();await page.waitForTimeout(300);
 check('resize interrupts drag safely',JSON.stringify(await order())===JSON.stringify(beforeCancel)&&await page.evaluate(()=>!homeDrag&&!document.querySelector('.home-drag-preview')));
 await page.route('**/api/home_layout',route=>route.fulfill({status:400,contentType:'application/json',body:'{"error":"测试保存失败"}'}));
 await page.locator('[data-home-handle=later]').focus();await page.keyboard.press('Space');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await page.evaluate(()=>homeSaveChain);await page.waitForTimeout(250);
 check('failed save rolls back and reports error',JSON.stringify(await order())===JSON.stringify(beforeCancel)&&await page.locator('#toast').textContent().then(t=>t.includes('布局未保存')));
 await page.unroute('**/api/home_layout');
 await page.locator('#home-reset').click();await page.evaluate(()=>homeSaveChain);await page.waitForTimeout(350);
 check('restore default is persistent',JSON.stringify(await order())===JSON.stringify(defaults)&&await page.evaluate(async()=>JSON.stringify((await api('state')).home_card_order)===JSON.stringify(HOME_CARD_IDS)));
  for(const layout of [['next','focus','status','douyin','later'],['douyin','status','focus','later','next'],['next','focus','douyin','later','status']]){
  await page.evaluate(layout=>applyHomeOrder(layout),layout);
  check('mixed-size order remains compact '+layout.indexOf('status'),await page.evaluate(()=>{const g=document.getElementById('home-cards'),n=getComputedStyle(g).gridTemplateColumns.split(/\s+/).length,i=homeOrder.indexOf('status');return document.querySelector('[data-home-card=status]').classList.contains('home-tile-wide')===(n>1&&n-i%n>=2)}));
  check('reordered cards do not overlap '+layout.indexOf('status'),await page.evaluate(()=>{const r=[...document.querySelectorAll('#home-cards article')].map(c=>c.getBoundingClientRect());return r.every((a,i)=>r.every((b,j)=>i===j||a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top))}));
 }
 await page.evaluate(()=>applyHomeOrder(HOME_CARD_IDS));
 await page.locator('[data-go-module=douyin]').click();await page.waitForTimeout(300);
 check('tile navigates to existing library',await page.evaluate(()=>currentModule==='douyin'&&document.querySelectorAll('.card').length===30));
 await page.evaluate(()=>{if(compactNavigation.matches)toggleNavigation()});await page.waitForTimeout(450);
 check('library keeps its secondary menu',await page.locator('#modulepanel').isVisible()&&await page.locator('#navtoggle').isVisible());
 await page.evaluate(()=>{selection.add(state.videos[1].id);pageNumber=2;render()});const selected=await page.evaluate(()=>[...selection]);
 await page.locator('#homemodule').click();await page.waitForTimeout(300);
 check('return to home hides submenu without losing library selection',await page.locator('#modulepanel').isHidden()&&await page.evaluate(()=>pageNumber===2&&selection.size===1));
 await page.locator('[data-home-queue]').click();await page.waitForTimeout(300);
 check('queue tile opens real queue in library',await page.locator('#queuepanel').isVisible()&&await page.evaluate(()=>currentModule==='douyin'));await page.locator('#closequeue').click();
 await page.locator('#homemodule').click();await page.waitForTimeout(300);
 check('layout updates did not alter processing jobs',await page.evaluate(before=>JSON.stringify(state.jobs)===before,jobsBefore));
 check('layout updates did not alter material records',await page.evaluate(before=>JSON.stringify(state.videos)===before,videosBefore));
 const fake={configured:false,date:await page.evaluate(()=>homeState.date),sources:[],actions:[],schedule:[],projects:[],waiting:[],links:[]};
 await page.route('**/api/home',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fake)}));await page.waitForFunction(()=>!homeBusy);await page.locator('#home-refresh').click();await page.waitForFunction(()=>homeState?.configured===false&&document.querySelectorAll('[data-home-card]').length===1);
 check('unbound personal notes do not hide real module data',await page.locator('#homeview').textContent().then(t=>t.includes('尚未绑定'))&&await page.locator('.collection-total strong').textContent()==='65');await page.unroute('**/api/home');await page.waitForFunction(()=>!homeBusy);await page.locator('#home-refresh').click();
 await page.waitForFunction(()=>homeState?.configured);await page.setViewportSize({width:1440,height:920});await page.waitForTimeout(4700);
 await page.screenshot({path:output+'/home-cards-desktop.png'});
 check('no page errors',errors.length===0);
 return {ok:true,checks:checks.length,moved,errors,layoutWrites:mutations.filter(p=>p==='/api/home_layout').length};
}
